AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sensor API for Fire & CO2 Company

Globals:
  Function:
    Timeout: 3
    Runtime: python3.12
    Architectures:
      - x86_64

Resources:

  CreateSensorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: sensors/
      Handler: app.lambda_handler
      Policies:
        - DynamoDBWritePolicy:
          TableName: !Ref SensorsTable
      Events:
        CreateSensorApi:
          Type: Api
          Properties:
            Environment:
              Variables:
                SENSORS_TABLE_NAME: !Ref SensorsTable
            Path: /sensors
            Method: post

  CreateReadingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: readings/
      Handler: app.lambda_handler
      Events:
        CreateReadingApi:
          Type: Api
          Properties:
            Path: /readings
            Method: post

  GetAlertsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: alerts/
      Handler: app.lambda_handler
      Events:
        GetAlertsApi:
          Type: Api
          Properties:
            Path: /alerts
            Method: get

  SensorsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FireCO2Sensors
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S # String type for sensor_id
      KeySchema:
        - AttributeName: id
          KeyType: HASH # Primary key
      BillingMode: PAY_PER_REQUEST # On-demand capacity
